# Default values for nginx-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: argoproj/rollouts-demo  
  tag: "blue"



  pre_repository: argoproj/rollouts-demo
  pre_tag: "green"

