apiVersion: v1
kind: Service
metadata:
  name: virtlet
  namespace: argo-my-test
spec:
  ports:
  - port: 80
    targetPort: 8080    
  type: NodePort
  selector:
    app.target: virtlet-template
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: virtlet-preview
  namespace: argo-my-test
spec:
  ports:
  - port: 80
    targetPort: 8080    
    name: http
  type: NodePort
  selector:
    app.target: virtlet-template-preview 
    release: {{ .Release.Name }}