apiVersion: v1
kind: Service
metadata:
  name: virtlet
  namespace: argo-my-test
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: virtlet
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: virtlet-preview
  namespace: argo-my-test
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: virtlet-preview    
    release: {{ .Release.Name }}